- name: Coping {{COMPONENT}} repo 
  ansible.builtin.copy:
    src: redis.repo 
    dest: /etc/yum.repos.d/redis.repo  

- name: Install {{COMPONENT}} 
  ansible.builtin.package:
    name: 
    state: present  