- name: Coping {{COMPONENT}} repo 
  ansible.builtin.copy:
    src: redis.repo 
    dest: /etc/yum.repos.d/redis.repo  

- name: Install {{COMPONENT}} 
  ansible.builtin.package:
    name: redis-6.2.7
    state: present  

- name: Updating MongoDB Config
  ansible.builtin.replace:
    path: /etc/mongod.conf
    regexp: '127.0.0.1'
    replace: '0.0.0.0'