- name: Coping {{COMPONENT}} repo 
  ansible.builtin.copy:
    src: redis.repo 
    dest: /etc/yum.repos.d/redis.repo  

- name: Install  
  ansible.builtin.package:
    name: "{{item}}"
    state: present  