- name: Coping mongodb repo file 
  ansible.builtin.copy:
    src: mongod.repo 
    dest: /etc/yum.repod.d/mongodb.repo  


- name: Installing Nginx
  ansible.builtin.package:
    name: mongodb-org 
    state: present 