- name: Coping mongodb repo file 
  ansible.builtin.copy:
    src: mongod.repo 
    dest: /etc/yum.repod.d/mongodb.repo  

- name: Installing MongoDb
  ansible.builtin.yum:
    name: mongodb-org 
    state: present 

vim /etc/mongod.conf
- name: Updating MongoDB Config
  ansible.builtin.replace:
    path: /etc/hosts
    regexp: '(\s+)old\.host\.name(\s+.*)?$'
    replace: '\1new.host.name\2'