- name: Coping mongodb repo file 
  ansible.builtin.copy:
    src: mongod.repo 
    dest: /etc/yum.repod.d/mongodb.repo  

- name: Installing MongoDb
  ansible.builtin.yum:
    name: mongodb-org 
    state: present 