- name: demo on variables 
  hosts: all  # all is default group in inventory file which includes everything 
  vars:       # Global varibale
      URL: play.google.com  
  tasks: 
    - name: pritning URL  
      ansible.builtin.debug:
        msg: Url that we print is {{URL}}  

    - name: pritning URL with quotes  
      ansible.builtin.debug:
        msg: "{{ URL }}" 
      vars:                 # local variable 
        URL: task.google.com 

    - name: Printing URL from CLI 
      ansible.builtin.debug:
        msg: URL_CLI is {{ CLI_URL }} 


# When to use "" for variables ? when the variable is the start of the line or the only one in the print list 

# local variable > global variable 
