- name: demo on ingore errors 
  hosts: all  
  vars:       # Global varibale
      URL: play.google.com 
  # vars_prompt:
  #     - name: URL 
  #       prompt: Enter URL  
  #       private: no
  tasks: 
    - name: pritning URL  
      ansible.builtin.debug:
        msg: Url that we print is {{ URL }}  