- name: demo on conditions 
  hosts: all  
  tasks: 
    - name: Run this when the OS is CentOS 
      ansible.builtin.debug: 
          msg: Hello to centos  

    - name: Run this when the OS is Ubuntu 
      ansible.builtin.debug: 
          msg: Hello to ubuntu  